### ISSUE TITLE
Driver's app, after choosing a ride, the passenger's phone number should appear on the screen.

### ISSUE THREAD

**Issue by OrleeTal** [Ezer-Lachaim/EZLA#195] opened 2023-08-26 20:00 UTC
1. Driver's app, after choosing a ride, the passenger's phone number should appear on the screen.
2. Add instruction recommending calling the passenger

<img width="600" alt="52b46ef7-35ff-4ec8-9882-509ee93ea849" src="https://github.com/Ezer-Lachaim/EZLA/assets/137285852/aed3e08c-92e7-4160-9f65-65c787e67282">

**Comment by iddanh** [comment] 2023-08-27 06:25
This is a duplicate of https://github.com/Ezer-Lachaim/EZLA/issues/174, closing this one

**Closed by iddanh** 2023-08-27 06:25 UTC
Labels: enhancement, High
