### ISSUE TITLE
Verify that the Driver's login details are saved. And do not require the driver to enter them every time he enters the app

### ISSUE THREAD

**Issue by OrleeTal** [Ezer-Lachaim/EZLA#321] opened 2023-11-20 19:48 UTC
Could you verify that the Driver's login details are saved? And do not require the driver to enter them every time he enters the app.
The call center reported that it doesn't always work.

**Comment by LEVI-RIVKIN** [comment] 2023-11-22 09:21
@OrleeTal What exactly do you mean? I think this is a duplicate of https://github.com/Ezer-Lachaim/EZLA/issues/318 and https://github.com/Ezer-Lachaim/EZLA/issues/254

**Comment by OrleeTal** [comment] 2023-11-22 09:47
This is feedback from the call center that some drivers have to enter their
login details every time they log in, instead of the system
remembering them and entering them automatically.
Maybe it was fixed, I wanted to make sure that this is the way the system
is designed to work - not need to log in again unless it expired.

**Comment by LEVI-RIVKIN** [comment] 2023-11-22 10:53
@OrleeTal Currently the expiration time is one hour.

When I test locally the driver is recognized when entering again few minutes after the login.

Are you sure they have to re-enter their credentials every time they open the app, even in cases where they re-open the app, let's say one minute after the last login?

If that is the case please provide some more details, like a name of a driver, OS, app or browser, which browser etc.
If you can also provide a video of the issue it'll be great.

**Comment by OrleeTal** [comment] 2023-11-22 21:18
@Levi Rivkin ***@***.***> I'll ask the call center to recheck,
and I'll share with you any information I receive.

Is one one-hour expiration time standard practice?
It seems very short to me.

**Comment by LEVI-RIVKIN** [comment] 2023-11-23 10:15
@OrleeTal The one hour expiration is not standard. It just means that this issue is indeed a duplicate of https://github.com/Ezer-Lachaim/EZLA/issues/254 and https://github.com/Ezer-Lachaim/EZLA/issues/318 and the only thing needed is to extend the login session expiration.

**Closed** 2024-02-16 06:12 UTC
Labels: enhancement
